apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: organizers-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: organizers-api
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 90
status:
  currentCPUUtilizationPercentage: 0
  currentReplicas: 1
  desiredReplicas: 1