apiVersion: apps/v1
kind: Deployment
metadata:
  name: organizers-api
  labels:
    app: organizers-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: organizers-api
  template:
    metadata:
      labels:
        app: organizers-api
    spec:
      containers:
        - name: organizers-api
          image: localhost:3333/organizers_api:${{ GITHUB.SHA }}
          imagePullPolicy: Never
          ports:
          - containerPort: 3333
          envFrom:
          - secretRef:
              name: api-secrets
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi
