apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
type: Opaque
data:
  DATABASE_URL: bW9uZ29kYitzcnY6Ly9QdWJieUFkbWluOldlQWFSUDdCdkpCN1NaSkEtQHB1YmJ5Y2x1c3Rlci56MGNwb3JtLm1vbmdvZGIubmV0L3B1YmJ5X2RiP3JldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eQ==
  PORT: MzMzMw==