apiVersion: v1
kind: Service
metadata:
  name: organizers-api-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 3333
      targetPort: 3333
      nodePort: 30037
  selector:
    app: organizers-api